#!/bin/bash
echo "Para conectar con GitHub, ejecuta estos comandos:"
echo ""
echo "1. Reemplaza 'TU_USUARIO' con tu nombre de usuario de GitHub:"
echo "git remote add origin https://github.com/TU_USUARIO/restaurant_template.git"
echo ""
echo "2. Sube el código:"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "3. Deploy a GitHub Pages:"
echo "npm run deploy"
echo ""
echo "Una vez que ejecutes estos comandos, tu sitio estará disponible en:"
echo "https://TU_USUARIO.github.io/restaurant_template/"
